export { Dashboard } from './Dashboard'
export { Login } from './Login'
export { Register } from './Register'
export { Products } from './Products'
export { Customers } from './Customers'
export { Orders } from './Orders'
export { Invoices } from './Invoices'
export { Members } from './Members'
export { Settings } from './Settings'
export { Admin } from './Admin'
export { WorkspaceRegistration } from './WorkspaceRegistration'
export { POS } from './POS'
export { Sales } from './Sales'
export { WorkspaceConfiguration } from './WorkspaceConfiguration'
export { default as WhatsApp } from './WhatsApp'
